In [10]:
import numpy as np

In [11]:
type(np.zeros(12))

numpy.ndarray

In [13]:
x_list = [i for i in range(12)]
x = np.array(x_list, dtype=np.float64)
print(x)

[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11.]


In [19]:
y = np.array([1/i for i in range(1, 13)])
print(y)

[1.         0.5        0.33333333 0.25       0.2        0.16666667
 0.14285714 0.125      0.11111111 0.1        0.09090909 0.08333333]


In [20]:
x+y

array([ 1.        ,  1.5       ,  2.33333333,  3.25      ,  4.2       ,
        5.16666667,  6.14285714,  7.125     ,  8.11111111,  9.1       ,
       10.09090909, 11.08333333])

In [21]:
np.mean(x), np.std(x)

(5.5, 3.452052529534663)

In [22]:
2*x

array([ 0.,  2.,  4.,  6.,  8., 10., 12., 14., 16., 18., 20., 22.])

In [24]:
x*np.array([2 for i in range(12)])

array([ 0.,  2.,  4.,  6.,  8., 10., 12., 14., 16., 18., 20., 22.])

In [25]:
np.sin(x)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849,
       -0.54402111, -0.99999021])